import { v4 as uuidv4 } from "uuid";

export const seedCategories = [
    { id: uuidv4(), name: "Electronics", slug: "electronics", description: "Electronic devices and accessories" },
    { id: uuidv4(), name: "Clothing", slug: "clothing", description: "Fashion and apparel" },
    { id: uuidv4(), name: "Home & Kitchen", slug: "home-kitchen", description: "Home improvement and kitchen essentials" },
    { id: uuidv4(), name: "Books", slug: "books", description: "Books and educational materials" },
    { id: uuidv4(), name: "Sports", slug: "sports", description: "Sports equipment and gear" },
];

export const seedProducts = [
    {
        id: uuidv4(),
        name: "Wireless Bluetooth Headphones",
        slug: "wireless-bluetooth-headphones",
        description: "Premium wireless Bluetooth headphones with noise cancellation, 30-hour battery life, and comfortable over-ear design. Perfect for music lovers and professionals.",
        price: "7999.00",
        compareAtPrice: "9999.00",
        stock: 50,
        sku: "WBH-001",
        brand: "TechPro",
        isFeatured: true,
        rating: "4.5",
        reviewCount: 128,
    },
    {
        id: uuidv4(),
        name: "Smart Watch Pro",
        slug: "smart-watch-pro",
        description: "Advanced smartwatch with health monitoring, GPS tracking, and 7-day battery life. Water resistant to 50 meters.",
        price: "12999.00",
        compareAtPrice: "15999.00",
        stock: 30,
        sku: "SWP-001",
        brand: "TechPro",
        isFeatured: true,
        rating: "4.3",
        reviewCount: 85,
    },
    {
        id: uuidv4(),
        name: "Cotton Casual T-Shirt",
        slug: "cotton-casual-tshirt",
        description: "Comfortable 100% organic cotton t-shirt. Available in multiple colors. Machine washable.",
        price: "999.00",
        compareAtPrice: "1499.00",
        stock: 200,
        sku: "CCT-001",
        brand: "ComfortWear",
        isFeatured: false,
        rating: "4.1",
        reviewCount: 312,
    },
    {
        id: uuidv4(),
        name: "Non-Stick Cookware Set",
        slug: "non-stick-cookware-set",
        description: "10-piece non-stick cookware set including pots, pans, and utensils. Dishwasher safe. Suitable for all cooktops.",
        price: "4999.00",
        stock: 25,
        sku: "NCS-001",
        brand: "HomeChef",
        isFeatured: true,
        rating: "4.6",
        reviewCount: 67,
    },
    {
        id: uuidv4(),
        name: "Yoga Mat Premium",
        slug: "yoga-mat-premium",
        description: "Extra thick premium yoga mat with non-slip surface. Includes carrying strap. Eco-friendly materials.",
        price: "1999.00",
        compareAtPrice: "2499.00",
        stock: 75,
        sku: "YMP-001",
        brand: "FitLife",
        isFeatured: false,
        rating: "4.4",
        reviewCount: 203,
    },
];
